--
-- PostgreSQL database dump
--

\restrict GXhiW0GSIGz5DHtkVpNMs3v7585YMU31xM8GC2dalssziwmlQLQ2lt98TPS0Nwy

-- Dumped from database version 14.22 (Debian 14.22-1.pgdg13+1)
-- Dumped by pg_dump version 14.22 (Debian 14.22-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ALEX_DENT; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA "ALEX_DENT";


ALTER SCHEMA "ALEX_DENT" OWNER TO postgres;

--
-- Name: alex_dent; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA alex_dent;


ALTER SCHEMA alex_dent OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE "ALEX_DENT".auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE "ALEX_DENT".django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE "ALEX_DENT".django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE "ALEX_DENT".django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "ALEX_DENT".django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: ALEX_DENT; Owner: postgres
--

CREATE TABLE "ALEX_DENT".django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE "ALEX_DENT".django_session OWNER TO postgres;

--
-- Name: auth_group; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE alex_dent.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE alex_dent.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE alex_dent.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE alex_dent.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE alex_dent.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE alex_dent.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE alex_dent.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE alex_dent.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

ALTER TABLE alex_dent.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME alex_dent.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE alex_dent.django_session OWNER TO postgres;

--
-- Name: medical_clinics; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.medical_clinics (
    id integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE alex_dent.medical_clinics OWNER TO postgres;

--
-- Name: medical_clinics_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

CREATE SEQUENCE alex_dent.medical_clinics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE alex_dent.medical_clinics_id_seq OWNER TO postgres;

--
-- Name: medical_clinics_id_seq; Type: SEQUENCE OWNED BY; Schema: alex_dent; Owner: postgres
--

ALTER SEQUENCE alex_dent.medical_clinics_id_seq OWNED BY alex_dent.medical_clinics.id;


--
-- Name: patients; Type: TABLE; Schema: alex_dent; Owner: postgres
--

CREATE TABLE alex_dent.patients (
    id integer NOT NULL,
    full_name character varying(200) NOT NULL
);


ALTER TABLE alex_dent.patients OWNER TO postgres;

--
-- Name: patients_id_seq; Type: SEQUENCE; Schema: alex_dent; Owner: postgres
--

CREATE SEQUENCE alex_dent.patients_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE alex_dent.patients_id_seq OWNER TO postgres;

--
-- Name: patients_id_seq; Type: SEQUENCE OWNED BY; Schema: alex_dent; Owner: postgres
--

ALTER SEQUENCE alex_dent.patients_id_seq OWNED BY alex_dent.patients.id;


--
-- Name: medical_clinics id; Type: DEFAULT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.medical_clinics ALTER COLUMN id SET DEFAULT nextval('alex_dent.medical_clinics_id_seq'::regclass);


--
-- Name: patients id; Type: DEFAULT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.patients ALTER COLUMN id SET DEFAULT nextval('alex_dent.patients_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-08 19:05:04.968831+00
2	contenttypes	0002_remove_content_type_name	2026-04-08 19:05:05.008569+00
3	auth	0001_initial	2026-04-08 19:05:05.408733+00
4	auth	0002_alter_permission_name_max_length	2026-04-08 19:05:05.43195+00
5	auth	0003_alter_user_email_max_length	2026-04-08 19:05:05.458865+00
6	auth	0004_alter_user_username_opts	2026-04-08 19:05:05.486491+00
7	auth	0005_alter_user_last_login_null	2026-04-08 19:05:05.517409+00
8	auth	0006_require_contenttypes_0002	2026-04-08 19:05:05.530298+00
9	auth	0007_alter_validators_add_error_messages	2026-04-08 19:05:05.55017+00
10	auth	0008_alter_user_username_max_length	2026-04-08 19:05:05.607601+00
11	auth	0009_alter_user_last_name_max_length	2026-04-08 19:05:05.637141+00
12	auth	0010_alter_group_name_max_length	2026-04-08 19:05:05.669682+00
13	auth	0011_update_proxy_permissions	2026-04-08 19:05:05.689114+00
14	auth	0012_alter_user_first_name_max_length	2026-04-08 19:05:05.708475+00
15	sessions	0001_initial	2026-04-08 19:05:05.7839+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: ALEX_DENT; Owner: postgres
--

COPY "ALEX_DENT".django_session (session_key, session_data, expire_date) FROM stdin;
0hqsiyhg9wovgouha4xtg7fnfyqfuqh3	eyJuZXh0X3VybCI6Ii9mYXZpY29uLmljbyJ9:1wAYce:7sY9BcvZnuLq3dYcoe78vOxIYsjVfUHdxj9G7CIHNm0	2026-04-08 20:31:32.001131+00
df7kqq2s8fk4srhhy4w4m5bsbcshgo1d	eyJuZXh0X3VybCI6Ii9mYXZpY29uLmljbyJ9:1wAZCg:OQpb1ToFaT9RxcQHRLJN8lFNCFtg_-25zf0_pZkobCs	2026-04-08 21:08:46.503693+00
1rzg5j9zjdojxamiaj5w8ivz9koa0el2	eyJuZXh0X3VybCI6Ii9mYXZpY29uLmljbyJ9:1wAnq7:xcdfQcM0DwUS0VaRk8iXNcF6vtZKwlng4Ze7cawcrPg	2026-04-09 12:46:27.149084+00
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add user	3	add_user
10	Can change user	3	change_user
11	Can delete user	3	delete_user
12	Can view user	3	view_user
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	auth	user
4	contenttypes	contenttype
5	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-09 11:53:40.321057+00
2	contenttypes	0002_remove_content_type_name	2026-04-09 11:53:40.38292+00
3	auth	0001_initial	2026-04-09 11:53:40.71923+00
4	auth	0002_alter_permission_name_max_length	2026-04-09 11:53:40.739819+00
5	auth	0003_alter_user_email_max_length	2026-04-09 11:53:40.765361+00
6	auth	0004_alter_user_username_opts	2026-04-09 11:53:40.790665+00
7	auth	0005_alter_user_last_login_null	2026-04-09 11:53:40.821112+00
8	auth	0006_require_contenttypes_0002	2026-04-09 11:53:40.835576+00
9	auth	0007_alter_validators_add_error_messages	2026-04-09 11:53:40.866423+00
10	auth	0008_alter_user_username_max_length	2026-04-09 11:53:40.921827+00
11	auth	0009_alter_user_last_name_max_length	2026-04-09 11:53:40.945324+00
12	auth	0010_alter_group_name_max_length	2026-04-09 11:53:40.976952+00
13	auth	0011_update_proxy_permissions	2026-04-09 11:53:40.996711+00
14	auth	0012_alter_user_first_name_max_length	2026-04-09 11:53:41.019832+00
15	sessions	0001_initial	2026-04-09 11:53:41.076639+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.django_session (session_key, session_data, expire_date) FROM stdin;
gfqom4kjr1xdy3s1um84zz9fxhkstn2q	eyJuZXh0X3VybCI6Ii9mYXZpY29uLmljbyJ9:1wAo14:bXTXQJc769M3FhSIJXJ0jp-I0gsPie3tH0RjchXA22k	2026-04-09 12:57:46.486718+00
\.


--
-- Data for Name: medical_clinics; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.medical_clinics (id, name) FROM stdin;
\.


--
-- Data for Name: patients; Type: TABLE DATA; Schema: alex_dent; Owner: postgres
--

COPY alex_dent.patients (id, full_name) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_permission_id_seq', 20, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".django_content_type_id_seq', 5, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: ALEX_DENT; Owner: postgres
--

SELECT pg_catalog.setval('"ALEX_DENT".django_migrations_id_seq', 15, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_permission_id_seq', 20, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.django_content_type_id_seq', 5, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.django_migrations_id_seq', 15, true);


--
-- Name: medical_clinics_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.medical_clinics_id_seq', 1, false);


--
-- Name: patients_id_seq; Type: SEQUENCE SET; Schema: alex_dent; Owner: postgres
--

SELECT pg_catalog.setval('alex_dent.patients_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: medical_clinics medical_clinics_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.medical_clinics
    ADD CONSTRAINT medical_clinics_pkey PRIMARY KEY (id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON "ALEX_DENT".auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON "ALEX_DENT".auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON "ALEX_DENT".auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON "ALEX_DENT".auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON "ALEX_DENT".auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON "ALEX_DENT".auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON "ALEX_DENT".auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON "ALEX_DENT".auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON "ALEX_DENT".auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON "ALEX_DENT".django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: ALEX_DENT; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON "ALEX_DENT".django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON alex_dent.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON alex_dent.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON alex_dent.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON alex_dent.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON alex_dent.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON alex_dent.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON alex_dent.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON alex_dent.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON alex_dent.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON alex_dent.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: alex_dent; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON alex_dent.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES "ALEX_DENT".auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES "ALEX_DENT".auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES "ALEX_DENT".django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES "ALEX_DENT".auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES "ALEX_DENT".auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES "ALEX_DENT".auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: ALEX_DENT; Owner: postgres
--

ALTER TABLE ONLY "ALEX_DENT".auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES "ALEX_DENT".auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES alex_dent.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES alex_dent.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES alex_dent.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES alex_dent.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES alex_dent.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES alex_dent.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: alex_dent; Owner: postgres
--

ALTER TABLE ONLY alex_dent.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES alex_dent.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict GXhiW0GSIGz5DHtkVpNMs3v7585YMU31xM8GC2dalssziwmlQLQ2lt98TPS0Nwy

