"""
Django settings for alex_proj_dent project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o3hfsgs&m9r^6rskx)90g+7yh*b(enb!o5tbirt-87z+u7$!4d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "expertise-fed-cheapest-jackson.trycloudflare.com",
    "alexeskmaq.onrender.com",  # أضف هذا السطر
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'alex_proj_dent.cincopra',  # ✅ أضف هذا
    # أو 'cincopra' فقط إذا كنت تفضل المسار المختصر
]
# alex_proj_dent/settings.py

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # ✅ المسار الصحيح لمجلد cincopra
    'alex_proj_dent.cincopra.middleware.LoginRequiredMiddleware',
]

# أو إذا كنت تفضل استخدام المسار المختصر:
# 'cincopra.middleware.LoginRequiredMiddleware',

ROOT_URLCONF = 'alex_proj_dent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'alex_proj_dent' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alex_proj_dent.wsgi.application'
import os

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'alex_dent',
        'USER': 'postgres',
        'PASSWORD': 'esk777513858',
        'HOST': 'postgres_db',
        'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'  # تغيير إلى العربية
TIME_ZONE = 'Asia/Riyadh'  # تغيير المنطقة الزمنية
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'alex_proj_dent' / 'static',
]

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'alex_proj_dent' / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================
# إعدادات الجلسات (Session Settings)
# ============================================
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # ساعة واحدة (3600 ثانية)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # لا تنتهي الجلسة عند إغلاق المتصفح
SESSION_SAVE_EVERY_REQUEST = True  # حفظ الجلسة مع كل طلب (مهم للميدلوير)


# ============================================
# إعدادات رسائل التنبيه (Messages Settings)
# ============================================
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}
# Force schema for all database queries
from django.db.backends.signals import connection_created

def set_search_path(sender, connection, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute('SET search_path = alex_dent, public;')
        # للتأكد من أنه اشتغل
        cursor.execute('SHOW search_path;')
        result = cursor.fetchone()
        print(f"Search path set to: {result}")

connection_created.connect(set_search_path)