import json
import traceback
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from ..view.db_process import process_db_ora_mysql

@csrf_exempt
def ins_clin_data(request):
    db = process_db_ora_mysql()

    if request.method != "POST":
        return JsonResponse({
            "success": False,
            "error_code": "INVALID_METHOD",
            "message": "الطلب غير صالح"
        })

    try:
        data = json.loads(request.body)

        # ================================
        # استقبال البيانات من الفورم الجديد
        # ================================
        clin_id = data.get('clin_code', '').strip()
        clin_name = data.get('clin_name_p', '').strip()
        manager_name = data.get('first_p', '').strip()
        username = data.get('user_p', '').strip()
        password = data.get('passwordu_p', '').strip()
        phone_number = data.get('phone_p', '').strip()
        address = data.get('address', '').strip()
        email = data.get('mang_e', '').strip()

        print("🔹 البيانات المستلمة:", data)

        # ================================
        # 1️⃣ التحقق من وجود اسم المستخدم مسبقاً
        # ================================
        check_user = {
            "MEDICAL_CLINICS": [{"select": True, "condition": f"USERNAME = '{username}'"}]
        }

        user_exists = db.execute_bulk(check_user).get("select", {}).get("MEDICAL_CLINICS", [])

        if user_exists:
            return JsonResponse({
                "success": False,
                "error_code": "USER_EXISTS",
                "message": f"اسم المستخدم '{username}' مستخدم مسبقاً"
            })

        # ================================
        # 2️⃣ تجهيز البيانات للإدخال
        # ================================
        prancacc1 = {
            "CLINIC_ID": clin_id,
            "CLINIC_NAME": clin_name,
            "MANAGER_NAME": manager_name,
            "USERNAME": username,
            "PASSWORD": password,
            "PHONE_NUMBER": phone_number,
            "ADDRESS": address,
            "EMAIL": email
        }

        # حذف الحقول الفارغة
        prancacc1 = {k: v for k, v in prancacc1.items() if v not in [None, ""]}

        # ================================
        # 3️⃣ تنفيذ الإدخال
        # ================================
        '''insert_data = {
            "MEDICAL_CLINICS": [{"insert": True, **prancacc1}]
        }

        db.execute_bulk(insert_data)
        db.connection.commit()'''

            # 🔥 مهم: لازم تجيب clin_id و patient_row من result
        clin_id = data.get('clin_code', '').strip()
        print(" # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥 # 🔥-clin_id=",clin_id)
            #patient_row = result.get("patient_row")

            # =============================
            # تعريف الجداول
            # =============================
        CLEN = {
    'DOCTOR_ID': 'NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    'DOCTOR_NAME': 'VARCHAR2(100 CHAR)',
    'USERNAME': 'VARCHAR2(50 CHAR)',
    'PASSWORD': 'VARCHAR2(200 CHAR)',
    'SPECIALTY': 'VARCHAR2(100 CHAR)',
    'PHONE_NUMBER': 'VARCHAR2(20 CHAR)',
    'ADDRESS': 'VARCHAR2(200 CHAR)',
    'EMAIL': 'VARCHAR2(100 CHAR)'
}

        DOC_TIME_CLIN = {
                'DOCTOR_ID': 'NUMBER',
                'SATURDAY': 'VARCHAR2(50 BYTE)',
                'SUNDAY': 'VARCHAR2(50 BYTE)',
                'MONDAY': 'VARCHAR2(50 BYTE)',
                'TUESDAY': 'VARCHAR2(50 BYTE)',
                'WEDNESDAY': 'VARCHAR2(50 BYTE)',
                'THURSDAY': 'VARCHAR2(50 BYTE)',
                'FRIDAY': 'VARCHAR2(50 BYTE)'
            }

        DENTAL_CONDITIONS = {
                'ID': 'NUMBER',
                'CONDITION_NAME_AR': 'VARCHAR2(255 BYTE)',
                'CONDITION_NAME_EN': 'VARCHAR2(255 BYTE)',
                'CLINIC_ID': 'NUMBER'
            }

        VISITS = {
                'TREATMENT': 'VARCHAR2(255 BYTE)',
                'VISIT_DATE': 'DATE',
                'DOCTOR_ID': 'NUMBER',
                'PATIENT_NO': 'NUMBER',
                'PERIOD_NO': 'NUMBER ',
                'BOOK_CONFIRMATION': 'VARCHAR2(5 BYTE)',
                'EXAMS': 'VARCHAR2(80 BYTE)',
                'VISIT_NUMBER': 'NUMBER GENERATED BY DEFAULT AS IDENTITY',
                'NOTE': 'VARCHAR2(3000 BYTE)',
                'MEDCEN':'VARCHAR2(80 BYTE)'
            }
        SERV_PRIC = {
            'SERVICE_ID': 'NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
           'SERVICE_NAME': 'VARCHAR2(255 BYTE)',
            'PRICE': 'NUMBER(10,2)',
            'CLINIC_NUMBER': 'NUMBER(20)'
                }
            # =============================
            # أسماء الجداول
            # =============================
        CLEN_tab = f"CLIN{clin_id}"
        DOC_TIME_tab = f"DOC_TIME_CLIN{clin_id}"
        CONDITIONS_CLIN_tab = f"CONDITIONS_CLIN{clin_id}"
        VISITS_tab = f"VISITS_CLIN{clin_id}"
        servistab=f"SERVICE_PRICE_CLIN{clin_id}"

            # =============================
            # التنفيذ
            # =============================
        db.execute_bulk({
                "MEDICAL_CLINICS": [{"insert": True, **prancacc1}],
                CLEN_tab: [{
                    "create": True,
                    "columns": CLEN
                }],

                DOC_TIME_tab: [{
                    "create": True,
                    "columns": DOC_TIME_CLIN
                }],

                CONDITIONS_CLIN_tab: [{
                    "create": True,
                    "columns": DENTAL_CONDITIONS
                }],

                VISITS_tab: [{
                    "create": True,
                    "columns": VISITS
                }],
                 servistab: [{
                    "create": True,
                    "columns":SERV_PRIC
                }]
            })

        db.connection.commit()
        return JsonResponse({
            "success": True,
            "error_code": None,
            "message": f"تم إضافة العيادة {prancacc1.get('CLINIC_NAME')} برقم {prancacc1.get('CLINIC_ID')}",
            "clinic_id": clin_id
        })

    except Exception as e:
        db.connection.rollback()
        print("❌ خطأ كامل:", traceback.format_exc())
        return JsonResponse({
            "success": True,
            "error_code": "EXCEPTION",
            "message": str(e)
        })
